# Generated by Django 3.0.8 on 2021-07-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('University_or_board_Name', models.CharField(max_length=50)),
                ('Passing_Year', models.DateField()),
            ],
        ),
    ]
